SOURCE_PATH=beholder/webapp

.DEFAULT_GOAL := build

include ../common.mk

build: install

install: uwsgi_metrics

uwsgi_metrics:
	mkdir -p uwsgi_metrics

clean: clean_uwsgi_metrics

clean_uwsgi_metrics:
	rm -rf uwsgi_metrics
