SOURCE_PATH=beholder/webapp

.DEFAULT_GOAL := build

include ../common.mk

build: install

install: uwsgi_metrics

uwsgi_metrics:
	uwsgi_metrics

clean: uwsgi_metrics

uwsgi_metrics:
	rm -rf uwsgi_metrics
